// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npefzvebmnzipfgdwhca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wZWZ6dmVibW56aXBmZ2R3aGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNDI1NjEsImV4cCI6MjA3NzcxODU2MX0.g3bcVn13JlZy3K3p4G7bbmE3QU3A6LwEHNDSW1ZswAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});